apiVersion: v1
kind: Service
metadata:
  name: fleet-app-service
  namespace: fleet-dev # Expose the service in our new namespace
spec:
  selector:
    app: fleet-api # This selector targets the pods created by our Deployment
  ports:
    - protocol: TCP
      port: 80 # The port the service will be available on inside the cluster
      targetPort: 8000 # Forward traffic to the container's port 8000
  type: ClusterIP # This service is only reachable from within the cluster